//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRouter) DeepCopyInto(out *BGPRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRouter.
func (in *BGPRouter) DeepCopy() *BGPRouter {
	if in == nil {
		return nil
	}
	out := new(BGPRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRouterList) DeepCopyInto(out *BGPRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRouterList.
func (in *BGPRouterList) DeepCopy() *BGPRouterList {
	if in == nil {
		return nil
	}
	out := new(BGPRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRouterSpec) DeepCopyInto(out *BGPRouterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRouterSpec.
func (in *BGPRouterSpec) DeepCopy() *BGPRouterSpec {
	if in == nil {
		return nil
	}
	out := new(BGPRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRouterStatus) DeepCopyInto(out *BGPRouterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NestedVirtualization != nil {
		in, out := &in.NestedVirtualization, &out.NestedVirtualization
		*out = new(bool)
		**out = **in
	}
	if in.BGPPeers != nil {
		in, out := &in.BGPPeers, &out.BGPPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRouterStatus.
func (in *BGPRouterStatus) DeepCopy() *BGPRouterStatus {
	if in == nil {
		return nil
	}
	out := new(BGPRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRoutingConfig) DeepCopyInto(out *BGPRoutingConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRoutingConfig.
func (in *BGPRoutingConfig) DeepCopy() *BGPRoutingConfig {
	if in == nil {
		return nil
	}
	out := new(BGPRoutingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPRoutingConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRoutingConfigList) DeepCopyInto(out *BGPRoutingConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPRoutingConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRoutingConfigList.
func (in *BGPRoutingConfigList) DeepCopy() *BGPRoutingConfigList {
	if in == nil {
		return nil
	}
	out := new(BGPRoutingConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPRoutingConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRoutingConfigSpec) DeepCopyInto(out *BGPRoutingConfigSpec) {
	*out = *in
	out.CloudRouter = in.CloudRouter
	out.NCC = in.NCC
	out.FRR = in.FRR
	in.GCE.DeepCopyInto(&out.GCE)
	out.NodeSelector = in.NodeSelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRoutingConfigSpec.
func (in *BGPRoutingConfigSpec) DeepCopy() *BGPRoutingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BGPRoutingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPRoutingConfigStatus) DeepCopyInto(out *BGPRoutingConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloudRouterInterfaces != nil {
		in, out := &in.CloudRouterInterfaces, &out.CloudRouterInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastReconcileResult != nil {
		in, out := &in.LastReconcileResult, &out.LastReconcileResult
		*out = new(ReconcileResultStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPRoutingConfigStatus.
func (in *BGPRoutingConfigStatus) DeepCopy() *BGPRoutingConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BGPRoutingConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRouterSpec) DeepCopyInto(out *CloudRouterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRouterSpec.
func (in *CloudRouterSpec) DeepCopy() *CloudRouterSpec {
	if in == nil {
		return nil
	}
	out := new(CloudRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRSpec) DeepCopyInto(out *FRRSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRSpec.
func (in *FRRSpec) DeepCopy() *FRRSpec {
	if in == nil {
		return nil
	}
	out := new(FRRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCESpec) DeepCopyInto(out *GCESpec) {
	*out = *in
	if in.EnableNestedVirtualization != nil {
		in, out := &in.EnableNestedVirtualization, &out.EnableNestedVirtualization
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCESpec.
func (in *GCESpec) DeepCopy() *GCESpec {
	if in == nil {
		return nil
	}
	out := new(GCESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCCSpec) DeepCopyInto(out *NCCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCCSpec.
func (in *NCCSpec) DeepCopy() *NCCSpec {
	if in == nil {
		return nil
	}
	out := new(NCCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorSpec) DeepCopyInto(out *NodeSelectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorSpec.
func (in *NodeSelectorSpec) DeepCopy() *NodeSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileResultStatus) DeepCopyInto(out *ReconcileResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileResultStatus.
func (in *ReconcileResultStatus) DeepCopy() *ReconcileResultStatus {
	if in == nil {
		return nil
	}
	out := new(ReconcileResultStatus)
	in.DeepCopyInto(out)
	return out
}
