apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bgp-routing-system
resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
